name: Deployment Workflow
on:
  workflow_dispatch:

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard openresolv

      - name: Setup WireGuard
        run: |
          echo "${{ secrets.VPN_CONF }}" | base64 -d > /tmp/wg0.conf
          sudo mv /tmp/wg0.conf /etc/wireguard/wg0.conf
          sudo wg-quick up wg0

      - name: SSH to the server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no wellcomp-hp-deploy@www.jn.sfc.keio.ac.jp

      - name: Pull the code on the server
        run: |
          cd /srv/www/wellcomp
          git pull
