name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: dali server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: kenty
        key: ${{ secrets.WELLCOMP_SECRET }}
        port: 22
        script: |
          cd /home/www/public_html/rgs/wellcomp
          git pull origin master
          git status
        
        
